spring:
  application:
    name: task

  cloud:
    stream:
      binders:
        broker: localhost:9092
      kafka:
        binder:
          auto-create-topics: true

  kafka:
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.gabryel.task.entity
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  messages:
    default-locale: pt-BR
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: true

  data:
    mongodb:
      database: task
      uri: mongodb://localhost:27017/task?maxPoolSize=50&waitQueueTimeoutMS=2000
      auto-index-creation: true

via:
  cep:
    url: https://viacep.com.br/ws

kafka:
  task:
    notification-output: task-notification-v1