spring:
  application:
    name: task
  messages:
    default-locale: pt-BR
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: true
  data:
    mongodb:
      database: task
      uri: mongodb://localhost:27017/task?maxPoolSize=50&waitQueueTimeoutMS=2000
      auto-index-creation: true

via:
  cep:
    url: https://viacep.com.br/ws